import pandas as pd
import logging
from .utilities import validate_columns


def add_net_revenue(sales):
    """
    Calculate net revenue for each sales record after
    applying the discount percentage.
    """
    validate_columns(
        sales,
        [
            "quantity_sold",
            "unit_price",
            "discount_pct"
        ]
    )

    sales = sales.copy()

    sales["net_revenue"] = (
        sales["quantity_sold"]
        *
        sales["unit_price"]
        *
        (
            1 -
            sales["discount_pct"] / 100
        )
    )
    return sales

def revenue_by_region(sales):
    """
    Calculate total net revenue grouped by region.
    """
    return (
        sales
        .groupby("region")["net_revenue"]
        .sum()
        .reset_index()
        .sort_values(
            "net_revenue",
            ascending=False
        )
    )

def revenue_by_category(sales):
    """
    Calculate total net revenue grouped by product category.
    """

    return (
        sales
        .groupby("category")["net_revenue"]
        .sum()
        .reset_index()
        .sort_values(
            "net_revenue",
            ascending=False
        )
    )

def revenue_by_sales_rep(sales):
    """
    Calculate total net revenue generated by each sales representative.
    """

    return (
        sales
        .groupby("sales_rep")["net_revenue"]
        .sum()
        .reset_index()
        .sort_values(
            "net_revenue",
            ascending=False
        )
    )

def top_products(sales):
    """
    Return the top five products ranked by net revenue.
    """

    return (
        sales
        .groupby(
            [
                "product_id",
                "product_name"
            ]
        )["net_revenue"]
        .sum()
        .reset_index()
        .sort_values(
            "net_revenue",
            ascending=False
        )
        .head(5)
    )

def bottom_products(sales):
    """
    Return the bottom five products ranked by net revenue.
    """

    return (
        sales
        .groupby(
            [
                "product_id",
                "product_name"
            ]
        )["net_revenue"]
        .sum()
        .reset_index()
        .sort_values(
            "net_revenue",
            ascending=True
        )
        .head(5)
    )

def top_regions_by_volume(sales):
    """
    Return the top three regions based on quantity sold.
    """

    return (
        sales
        .groupby("region")
        ["quantity_sold"]
        .sum()
        .reset_index()
        .sort_values(
            "quantity_sold",
            ascending=False
        )
        .head(3)
    )

def top_return_reasons(returns):
    """
    Return the three most common product return reasons.
    """

    return (
        returns["return_reason"]
        .value_counts()
        .head(3)
        .reset_index()
    )


def return_rate_by_category(
    sales,
    returns
):
    """
    Calculate the return rate percentage for each product category.
    """

    merged = returns.merge(
        sales[
            [
                "order_id",
                "category"
            ]
        ],
        on="order_id",
        how="left"
    )

    total_orders = (
        sales
        .groupby("category")
        ["order_id"]
        .count()
    )

    total_returns = (
        merged
        .groupby("category")
        ["return_id"]
        .count()
    )

    result = pd.concat(
        [
            total_orders,
            total_returns
        ],
        axis=1
    )

    result.columns = [
        "orders",
        "returns"
    ]

    result = result.fillna(0)

    result["return_rate_pct"] = (
        result["returns"]
        /
        result["orders"]
    ) * 100

    return result.reset_index()


def inventory_health(
    inventory,
    sales
):
    """
    Identify products at stockout risk and estimate
    potential lost revenue.
    """

    validate_columns(
        inventory,
        [
            "product_id",
            "stock_available",
            "reorder_level",
            "reorder_flag"
        ]
    )

    validate_columns(
        sales,
        [
            "product_id",
            "unit_price"
        ]
    )

    avg_prices = (
        sales
        .groupby("product_id")
        ["unit_price"]
        .mean()
    )

    at_risk = inventory[
        inventory["reorder_flag"]
    ].copy()

    at_risk["avg_unit_price"] = (
        at_risk["product_id"]
        .map(avg_prices)
    )

    at_risk[
        "estimated_lost_revenue"
    ] = (
        (
            at_risk["reorder_level"]
            -
            at_risk["stock_available"]
        )
        *
        at_risk["avg_unit_price"]
    )

    return at_risk


def weekly_revenue_trend(
    sales
):
    """
    Generate weekly aggregated net revenue trends.
    """

    weekly = (
        sales
        .set_index("date")
        .resample("W")
        ["net_revenue"]
        .sum()
        .reset_index()
    )

    return weekly

def run_analytics(
    sales,
    inventory,
    returns
):
    """
    Execute all business analytics calculations and
    return results as a metrics dictionary.
    """

    try:
        sales = add_net_revenue(
            sales
        )

        return {
            "sales": sales,
            "region_revenue":
                revenue_by_region(
                    sales
                ),
            "category_revenue":
                revenue_by_category(
                    sales
                ),
            "sales_rep_revenue":
                revenue_by_sales_rep(
                    sales
                ),
            "top_products":
                top_products(
                    sales
                ),
            "bottom_products":
                bottom_products(
                    sales
                ),
            "top_regions":
                top_regions_by_volume(
                    sales
                ),
            "return_rate":
                return_rate_by_category(
                    sales,
                    returns
                ),
            "return_reasons":
                top_return_reasons(
                    returns
                ),
            "inventory_health":
                inventory_health(
                    inventory,
                    sales
                ),
            "weekly_trend":
                weekly_revenue_trend(
                    sales
                )
        }

    except Exception as e:

        logging.exception(
            f"Analytics processing failed: {e}"
        )

        raise